#!/usr/bin/env node
/* Regenerates sitemap.xml from js/registry.js. Run it, commit the result.
   This is NOT a build step — the site is still plain files and deploy is still
   `git push`; nothing runs this on the server. It exists because sitemap.xml was
   the one file kept in sync BY HAND with the registry, and a drill missing from
   it is a drill Google is never told about.

   It also writes <lastmod>, which is the reason it has to be a script: the date
   comes from the last commit that touched that drill's folder, so it is true
   without anyone remembering to change it. Google uses lastmod to decide what to
   recrawl and distrusts it when it is obviously stale, so a hand-kept one would
   be worse than none.

   Run AFTER committing the content, so the dates it reads are the real ones:
     node tools/build-sitemap.js && git add sitemap.xml && git commit -m 'sitemap'
*/
const fs = require('fs'), vm = require('vm'), { execSync } = require('child_process');

const BASE = 'https://artdaily.sadeali.com/';
const ctx = { window: {} };
vm.createContext(ctx);
vm.runInContext(fs.readFileSync('js/registry.js', 'utf8'), ctx);

/* 'soon' is a promise, not a page: a dashed card on the catalogue with nothing
   behind it. Listing one would hand Google a 404. */
const live = ctx.window.ARTDAILY_GAMES.filter(g => g.status === 'live');

function lastCommit(path) {
  try {
    const d = execSync(`git log -1 --format=%cs -- ${JSON.stringify(path)}`, { encoding: 'utf8' }).trim();
    return d || null;
  } catch (e) { return null; }
}

const entries = [
  { loc: BASE, lastmod: lastCommit('index.html') },
  ...live.map(g => {
    const dir = g.url ? null : g.slug;              /* an off-site override has no folder here */
    if (dir && !fs.existsSync(`${dir}/index.html`)) {
      console.error(`MISSING: ${g.slug} is 'live' in the registry but ${dir}/index.html does not exist`);
      process.exitCode = 1;
    }
    return { loc: g.url || BASE + g.slug + '/', lastmod: dir ? lastCommit(dir) : null };
  }),
  ...practicePages(),
  ...standalonePages(),
];

/* Pages that are neither a drill nor a guide. /privacy/ belongs in the index: it is
   the page a school IT reviewer looks for by name, and the one a "no account needed"
   claim has to be able to point at. Listed by existence rather than hard-coded so a
   future /for-teachers/ or /about/ is one folder. */
function standalonePages() {
  return ['privacy', 'for-teachers', 'about']
    .filter(d => fs.existsSync(`${d}/index.html`))
    .map(d => ({ loc: `${BASE}${d}/`, lastmod: lastCommit(d) }));
}

/* The chapter guides under practice/ are the one part of the site the registry does
   not describe: they are prose, not drills, so there is nothing to give them a
   registry entry. They are still the pages most worth being found — a drill page can
   win "ellipse practice", but only a guide reaches "perspective practice exercises",
   where page one is all long-form teaching. Leaving them out of the sitemap would
   hide exactly the content written to be found.

   Discovered from the filesystem rather than listed here, so writing a seventh guide
   is one folder and no edit to this script. _-prefixed files are skipped: they are
   briefs, not pages (the repo has .nojekyll, so anything here really is served). */
function practicePages() {
  if (!fs.existsSync('practice/index.html')) return [];
  const out = [{ loc: BASE + 'practice/', lastmod: lastCommit('practice/index.html') }];
  for (const name of fs.readdirSync('practice').sort()) {
    if (name.startsWith('_') || name.startsWith('.')) continue;
    const page = `practice/${name}/index.html`;
    if (!fs.statSync(`practice/${name}`).isDirectory() || !fs.existsSync(page)) continue;
    out.push({ loc: `${BASE}practice/${name}/`, lastmod: lastCommit(`practice/${name}`) });
  }
  return out;
}

const xml = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<!-- Generated by tools/build-sitemap.js from js/registry.js — do not hand-edit. -->',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  ...entries.map(e =>
    `  <url><loc>${e.loc}</loc>${e.lastmod ? `<lastmod>${e.lastmod}</lastmod>` : ''}</url>`),
  '</urlset>',
  '',
].join('\n');

fs.writeFileSync('sitemap.xml', xml);
console.log(`sitemap.xml: ${entries.length} URLs (1 page + ${live.length} drills + ${entries.length - 1 - live.length} guides & pages)`);
